import type { Course, Category, UserProfile } from '@/types/course'

export const categories: Category[] = [
  { id: '1', name: 'Web Development', icon: 'Code', courseCount: 45, slug: 'web-development' },
  { id: '2', name: 'Mobile Development', icon: 'Smartphone', courseCount: 28, slug: 'mobile-development' },
  { id: '3', name: 'Data Science', icon: 'BarChart', courseCount: 32, slug: 'data-science' },
  { id: '4', name: 'Design', icon: 'Palette', courseCount: 24, slug: 'design' },
  { id: '5', name: 'Marketing', icon: 'TrendingUp', courseCount: 19, slug: 'marketing' },
  { id: '6', name: 'Business', icon: 'Briefcase', courseCount: 21, slug: 'business' },
]

export const courses: Course[] = [
  {
    id: '1',
    title: 'Complete Web Development Bootcamp',
    description: 'Learn HTML, CSS, JavaScript, React, Node.js and more in this comprehensive bootcamp',
    thumbnail: '/placeholder-course-1.jpg',
    youtubeUrl: 'https://youtube.com/watch?v=example1',
    category: 'Web Development',
    instructor: 'John Smith',
    duration: '12h 30m',
    level: 'Beginner',
    views: 125000,
    enrolledCount: 8500,
    rating: 4.8,
    tags: ['HTML', 'CSS', 'JavaScript', 'React'],
    publishedAt: '2024-01-15',
  },
  {
    id: '2',
    title: 'Python for Data Science',
    description: 'Master Python programming and data analysis with pandas, numpy, and matplotlib',
    thumbnail: '/placeholder-course-2.jpg',
    youtubeUrl: 'https://youtube.com/watch?v=example2',
    category: 'Data Science',
    instructor: 'Sarah Johnson',
    duration: '8h 45m',
    level: 'Intermediate',
    views: 98000,
    enrolledCount: 6200,
    rating: 4.7,
    tags: ['Python', 'Data Analysis', 'Pandas', 'NumPy'],
    publishedAt: '2024-02-10',
  },
  {
    id: '3',
    title: 'UI/UX Design Fundamentals',
    description: 'Learn the principles of user interface and user experience design from scratch',
    thumbnail: '/placeholder-course-3.jpg',
    youtubeUrl: 'https://youtube.com/watch?v=example3',
    category: 'Design',
    instructor: 'Michael Chen',
    duration: '6h 20m',
    level: 'Beginner',
    views: 76000,
    enrolledCount: 5100,
    rating: 4.9,
    tags: ['UI Design', 'UX Design', 'Figma', 'Design Theory'],
    publishedAt: '2024-01-28',
  },
  {
    id: '4',
    title: 'React Native Mobile Apps',
    description: 'Build cross-platform mobile applications with React Native and Expo',
    thumbnail: '/placeholder-course-4.jpg',
    youtubeUrl: 'https://youtube.com/watch?v=example4',
    category: 'Mobile Development',
    instructor: 'Emily Rodriguez',
    duration: '10h 15m',
    level: 'Intermediate',
    views: 54000,
    enrolledCount: 3800,
    rating: 4.6,
    tags: ['React Native', 'Mobile', 'iOS', 'Android'],
    publishedAt: '2024-02-20',
  },
  {
    id: '5',
    title: 'Digital Marketing Masterclass',
    description: 'Complete guide to SEO, social media marketing, and content strategy',
    thumbnail: '/placeholder-course-5.jpg',
    youtubeUrl: 'https://youtube.com/watch?v=example5',
    category: 'Marketing',
    instructor: 'David Lee',
    duration: '7h 50m',
    level: 'Beginner',
    views: 89000,
    enrolledCount: 7200,
    rating: 4.5,
    tags: ['SEO', 'Social Media', 'Content Marketing', 'Analytics'],
    publishedAt: '2024-01-05',
  },
  {
    id: '6',
    title: 'Business Strategy & Leadership',
    description: 'Develop essential business skills and leadership qualities for career growth',
    thumbnail: '/placeholder-course-6.jpg',
    youtubeUrl: 'https://youtube.com/watch?v=example6',
    category: 'Business',
    instructor: 'Amanda Foster',
    duration: '5h 30m',
    level: 'Advanced',
    views: 42000,
    enrolledCount: 2900,
    rating: 4.7,
    tags: ['Leadership', 'Strategy', 'Management', 'Business'],
    publishedAt: '2024-02-15',
  },
]

export const mockUser: UserProfile = {
  id: '1',
  name: 'Alex Thompson',
  email: 'alex.thompson@example.com',
  avatar: '/placeholder-avatar.jpg',
  bio: 'Passionate learner exploring web development and data science. Always excited to learn new skills!',
  enrolledCourses: ['1', '2', '3'],
  completedCourses: ['3'],
  savedCourses: ['4', '5'],
  joinedAt: '2024-01-01',
}
